### ISSUE TITLE
This probably does not work as intended

### ISSUE THREAD

**Issue by mitar** [xintron/django-mongorunner#1]
This probably does not work as intended. Your code;

```
connect(db_name)
```

does not reconnect or change database if MongoEngine was already connected from `settings.py` because MongoEngine reuses connections if same alias is supplied. And in your case you are supplying default alias, which might already be connected somewhere else.

**Comment by xintron** [comment]
This is indeed true. This was just a quick cleanup for the testrunner I was using a while back when developing with django+mongoengine and thought that it could be of use for others as well. It should (hopefully, haven't been that uptodate with the changes in pymongo/mongoengine lately) be a quick fix checking if the database name already exists and if so generate a new random name.

**Comment by mitar** [comment]
https://github.com/MongoEngine/mongoengine/pull/51

**Comment by xintron** [comment]
Yes, this is an old library and I'll probably remove/delete it.
